"""Rule matching and message rendering for RuleBasedGameBridge."""

from __future__ import annotations

from typing import Any

from tiktok_event_gateway.bridge.models import GameRule, RuleCondition, RuleMessage, RuleParam
from tiktok_event_gateway.bridge.template_renderer import TemplateRenderer
from tiktok_event_gateway.bridge.utils import MISSING, convert_value, read_dot_path


class RuleEngine:
    """Match normalized events against loaded XML rules and render game messages."""

    def __init__(self, rules: list[GameRule], renderer: TemplateRenderer) -> None:
        self._rules_by_type: dict[str, list[GameRule]] = {}
        self._renderer = renderer
        for rule in rules:
            self._rules_by_type.setdefault(rule.event_type, []).append(rule)

    def render_messages(self, event: dict[str, Any]) -> list[dict[str, Any]]:
        """Return game JSON messages generated by all matching rules."""
        event_type = str(event.get("event_type", ""))
        messages: list[dict[str, Any]] = []
        for rule in self._rules_by_type.get(event_type, []):
            if not self._matches_rule(rule, event):
                continue
            rule_context = rule.to_template_context()
            for message in rule.messages:
                params = self._build_params(message, event)
                messages.append(
                    self._renderer.render(
                        message.template,
                        event=event,
                        params=params,
                        rule=rule_context,
                    )
                )
        return messages

    def _matches_rule(self, rule: GameRule, event: dict[str, Any]) -> bool:
        if rule.compact:
            return self._matches_compact_rule(rule, event)
        return all(self._matches_condition(condition, event) for condition in rule.conditions)

    def _matches_compact_rule(self, rule: GameRule, event: dict[str, Any]) -> bool:
        event_type = str(event.get("event_type", ""))
        if rule.event_type != event_type:
            return False
        if rule.event_value == "*":
            return True
        extracted = extract_compact_event_value(event)
        if extracted is MISSING or extracted is None:
            return False
        return str(extracted) == str(rule.event_value)

    def _matches_condition(self, condition: RuleCondition, event: dict[str, Any]) -> bool:
        actual = read_dot_path(event, condition.field, default=MISSING)
        if condition.operator == "exists":
            expected_exists = convert_value(condition.expected, "bool")
            actual_exists = actual is not MISSING and actual is not None
            return actual_exists is expected_exists
        if actual is MISSING or actual is None:
            return False

        expected = convert_value(condition.expected, condition.value_type)
        actual_converted = _safe_convert(actual, condition.value_type)
        if actual_converted is MISSING:
            return False

        if condition.ignore_case and isinstance(actual_converted, str) and isinstance(expected, str):
            actual_compare: Any = actual_converted.lower()
            expected_compare: Any = expected.lower()
        else:
            actual_compare = actual_converted
            expected_compare = expected

        if condition.operator == "equals":
            return actual_compare == expected_compare
        if condition.operator == "not_equals":
            return actual_compare != expected_compare
        if condition.operator == "contains":
            return str(expected_compare) in str(actual_compare)
        if condition.operator == "starts_with":
            return str(actual_compare).startswith(str(expected_compare))
        if condition.operator == "greater_than":
            return actual_compare > expected_compare
        if condition.operator == "less_than":
            return actual_compare < expected_compare
        return False

    def _build_params(self, message: RuleMessage, event: dict[str, Any]) -> dict[str, Any]:
        params: dict[str, Any] = {}
        for param in message.params:
            params[param.name] = self._resolve_param(param, event)
        return params

    def _resolve_param(self, param: RuleParam, event: dict[str, Any]) -> Any:
        if param.from_path:
            raw = read_dot_path(event, param.from_path, default=MISSING)
            if raw is MISSING or raw is None:
                raw = param.default
        elif param.value is not None:
            raw = param.value
        else:
            raw = param.default
        if raw is None:
            return None
        return convert_value(raw, param.value_type)


def extract_compact_event_value(event: dict[str, Any]) -> Any:
    """Extract the compact rule value from a normalized event.

    Mapping:
    - gift -> payload.gift_name
    - comment -> payload.comment
    - like/follow/join -> "*"
    """
    event_type = str(event.get("event_type", ""))
    if event_type == "gift":
        return read_dot_path(event, "payload.gift_name", default=MISSING)
    if event_type == "comment":
        return read_dot_path(event, "payload.comment", default=MISSING)
    if event_type in {"like", "follow", "join"}:
        return "*"
    return MISSING


def _safe_convert(value: Any, value_type: str) -> Any:
    try:
        return convert_value(value, value_type)
    except Exception:
        return MISSING
